server.port=8080
spring.application.name=project2backend

# React dev server URL 
app.frontend.base-url=http://localhost:5173

# --- Supabase Auth (JWT validation) ---
supabase.jwk-set-uri=https://bxmcjgylxpzrcpxmdzwf.supabase.co/auth/v1/.well-known/jwks.json
supabase.issuer=https://bxmcjgylxpzrcpxmdzwf.supabase.co/auth/v1

## Use H2 for local testing
#spring.datasource.url=jdbc:h2:mem:hikedb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#
## allows to see database in browser at localhost:8080/h2-console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.bxmcjgylxpzrcpxmdzwf
spring.datasource.password=gPZ8I7Z9bDb3GjzS

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never